---
name: Validate Homey App

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.9.0
          cache: 'npm'

      - name: Install Homey CLI
        run: npm install --no-optional homey

      - name: Validate Homey App
        run: npx homey app validate --level=publish
